### ISSUE TITLE
`bind` override `socket.setRawOption`

### ISSUE THREAD

**Issue by yyk808** [flomesh-io/pipy#188]
## TLDR
```js
// pipy this_file.js --reuse-port

pipy().task().onStart(new Message('Turn around')).connect('127.0.0.1:8000', {
  bind: '127.0.0.1:1234',
  onState: (conn) => {
    if(conn.state === 'open') {
      conn.socket.setRawOption(1, 15, new Data([1]))
    }
  },
}).listen('127.0.0.1:1234').print()
```
The code above won't work correctly.

## Reproduce
1. Setting up a server returning message.
```shell
pipy -e 'pipy().listen("127.0.0.1:8000").print().connect("127.0.0.1:1234")'
```
2. Using code in the tldr to get error log like:
```log
❯ pipy error.js --reuse-port
2024-06-27 21:49:31.069 [INF] [config]
2024-06-27 21:49:31.069 [INF] [config] Module /error.js
2024-06-27 21:49:31.069 [INF] [config] ================
2024-06-27 21:49:31.069 [INF] [config]
2024-06-27 21:49:31.069 [INF] [config]  [Listen on 1234 at 127.0.0.1]
2024-06-27 21:49:31.069 [INF] [config]  ----->|
2024-06-27 21:49:31.069 [INF] [config]        |
2024-06-27 21:49:31.069 [INF] [config]       print -->|
2024-06-27 21:49:31.069 [INF] [config]                |
2024-06-27 21:49:31.069 [INF] [config]  <-------------|
2024-06-27 21:49:31.069 [INF] [config]  
2024-06-27 21:49:31.069 [INF] [config]  [Task #1 ()]
2024-06-27 21:49:31.069 [INF] [config]  ----->|
2024-06-27 21:49:31.069 [INF] [config]        |
2024-06-27 21:49:31.069 [INF] [config]       connect -->|
2024-06-27 21:49:31.069 [INF] [config]                  |
2024-06-27 21:49:31.069 [INF] [config]  <---------------|
2024-06-27 21:49:31.069 [INF] [config]  
2024-06-27 21:49:31.069 [INF] [listener] Listening on TCP port 1234 at 127.0.0.1
2024-06-27 21:49:31.069 [ERR] connect() at line 1 column 58 in /error.js: bind: Address already in use
2024-06-27 21:49:31.069 [ERR] connect() at line 1 column 58 in /error.js: bind: Address already in use
2024-06-27 21:49:31.069 [ERR] connect() at line 1 column 58 in /error.js: bind: Address already in use
^C2024-06-27 21:49:32.175 [INF] [shutdown] Shutting down...
2024-06-27 21:49:32.175 [INF] [shutdown] Waiting for workers to drain...
2024-06-27 21:49:32.175 [INF] [listener] Stopped listening on TCP port 1234 at 127.0.0.1
```

3. Also, I've made a python equivalent. If everything works fine in pipy, the pjs code should act just like this.
```python
import socket

server = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
server.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEPORT, 1)

client = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
client.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEPORT, 1)

BIND = 1234
TARGET = 8000

try:
    client.bind(('127.0.0.1', BIND))
    server.bind(('127.0.0.1', BIND))

    server.listen(1)
    client.connect(('127.0.0.1', TARGET))

    client.sendall(b'Turn around')

    s, _ = server.accept()
    data = s.recv(16)
    s.close()

    print(data.decode())

finally:
    client.close()
    server.close()
```

## Reason
I tried to add a print in `src/socket.cpp` line 885 where we define `setRawOption`, it will only be called when not set `bind` option.
So it comes out that `bind` will override `setRawOption`.

**Comment by pajama-coder** [comment]
@yyk808 Yes, the logic of `connect()` filter wasn't quite right, it didn't actually open the socket by the time when onState is called with `'open'` state. I've fixed that in the latest commit, where `onState` happens after the socket is open and before calling `bind()`. That should be the right time for you to do `setsockopt()`.

As for the "Address already in use" errors, that's just normal since reuse-port is only meaningful for server-side sockets. I don't think that's a problem for pipy.

**Comment by keveinliu** [comment]
@yyk808 Fixed in commit ad5a517d26d14b6dd84d68016df68c0ddddaa791

**Comment by yyk808** [comment]
> @yyk808 Yes, the logic of `connect()` filter wasn't quite right, it didn't actually open the socket by the time when onState is called with `'open'` state. I've fixed that in the latest commit, where `onState` happens after the socket is open and before calling `bind()`. That should be the right time for you to do `setsockopt()`.
> 
> As for the "Address already in use" errors, that's just normal since reuse-port is only meaningful for server-side sockets. I don't think that's a problem for pipy.

 ad5a517d26d14b6dd84d68016df68c0ddddaa791 fixed state error, so the `setsockopt()` will get the socket native handle correctly. 

I'm convinced that "Address already in use" is indeed a bug because the `setsockopt()` is still now working correctly. If we print out the return value of this function, we will find that the errno is still not `0` but `22`.  
```cpp
#define	EINVAL		22	/* Invalid argument */
```

```js
pipy().task().onStart(new Message('Turn around')).connect('127.0.0.1:8000', {
	onState: (conn) => {
		if(conn.state === 'open') {
			console.info(conn.socket.setRawOption(1, 15, new Data([1])))
		}
	},
	bind: '127.0.0.1:1234'
})
```
![截图 2024-07-04 22-16-14](https://github.com/flomesh-io/pipy/assets/71858127/9496a2aa-33fe-45b8-91a0-4040004a79dd)
